apiVersion: v1
kind: Service
metadata:
  name: console
  namespace: console-system
spec:
  externalTrafficPolicy: Local
  type: LoadBalancer
  ports:
  - name: "https"
    port: 443
    targetPort: 6443
  selector:
    app: console   
    hypercloud: ui
