apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: traefik
    app.kubernetes.io/managed-by: tmax-cloud
    app.kubernetes.io/name: api-gateway
  name: api-gateway
  namespace: api-gateway-system
spec:
  ports:
  - name: traefik
    port: 9000
    protocol: TCP
    targetPort: traefik
  - name: web
    port: 80
    protocol: TCP
    targetPort: web
  - name: websecure
    port: 443
    protocol: TCP
    targetPort: websecure
  - name: k8s
    port: 6443
    protocol: TCP
    targetPort: k8s
  - name: kafka1
    port: 9001
    protocol: TCP
    targetPort: kafka1
  - name: kafka2
    port: 9002
    protocol: TCP
    targetPort: kafka2
  - name: kafka3
    port: 9003
    protocol: TCP
    targetPort: kafka3
  selector:
    app.kubernetes.io/instance: traefik
    app.kubernetes.io/name: api-gateway
    app.kubernetes.io/managed-by: tmax-cloud
  sessionAffinity: None
  type: LoadBalancer
