---
# https://doc.traefik.io/traefik/routing/providers/kubernetes-crd/#kind-tlsoption
# Traefik currently only uses the TLS Store named "default". This means that if you have two stores that are named default in different kubernetes namespaces, they may be randomly chosen. For the time being, please only configure one TLSSTore named default.
## TLSSTore : Allows to configure the default TLS store
apiVersion: traefik.containo.us/v1alpha1
kind: TLSStore
metadata:
  labels:
    app.kubernetes.io/instance: traefik
    app.kubernetes.io/managed-by: tmax-cloud
    app.kubernetes.io/name: api-gateway
  name: default
  namespace: api-gateway-system
spec:
  defaultCertificate:
    secretName: tmaxcloud-gateway-acme

