apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- 001_deploy.yaml
- 002_service.yaml
- 003_ingressroute.yaml
namespace: api-gateway-system
images:
- name: tmaxcloudck/hypercloud-console
  newName: docker.io/tmaxcloudck/hypercloud-console
  newTag: 5.0.40.0
