kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: jwt-decode-auth-cluster-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: jwt-decode-auth-cluster-role
subjects:
  - kind: ServiceAccount
    name: jwt-decode-auth
    namespace: api-gateway-system
