apiVersion: v1
kind: ServiceAccount
metadata:
  name: jwt-decode
  namespace: api-gateway-system

---
kind: Secret
apiVersion: v1
metadata:
  name: jwt-decode-token
  namespace: api-gateway-system
  annotations:
    kubernetes.io/service-account.name: jwt-decode
type: kubernetes.io/service-account-token
