apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - 000_namespace.yaml
  - 001_crd.yaml
  - 002_clusterissuer_selfsigned.yaml
commonLabels:
  app.kubernetes.io/instance: gateway
  app.kubernetes.io/managed-by: tmax-cloud
  app.kubernetes.io/name: api-gateway