---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tmaxcloud-gateway-selfsigned-front
  namespace: api-gateway-system
spec:
  secretName: tmaxcloud-gateway-selfsigned-front
  commonName: tmax-cloud
  subject:
    organizations:
      - "tmax-cloud"
  isCA: false
  usages:
    - digital signature
    - key encipherment
    - server auth
    - client auth
  dnsNames:
    - "tmax-cloud"
    - "@@DNS@@"
    - "*.@@DNS@@"
  issuerRef:
    kind: ClusterIssuer
    group: cert-manager.io
    name: tmaxcloud-issuer